### Layers : Fundamental blocks of Neural Network

In [1]:
import torch
from torch.nn import Linear, ReLU
import torch.nn as nn
import numpy as np
from torch.autograd import Variable

In [5]:
myLayer = Linear(in_features=10,out_features=5,bias=True)
inp = Variable(torch.randn(1,10))
# myLayer = Linear(in_features=10,out_features=5,bias=True)
myLayer(inp)

tensor([[ 0.8702, -0.8681,  0.5081,  0.5448,  0.6318]],
       grad_fn=<AddmmBackward>)

In [6]:
myLayer.weight

Parameter containing:
tensor([[-0.0256,  0.2792,  0.2624, -0.0304,  0.2309,  0.2417, -0.0947, -0.2373,
          0.0759, -0.2015],
        [-0.0094, -0.2294,  0.1403, -0.2585,  0.1928,  0.0216, -0.2681,  0.1157,
         -0.1522,  0.2602],
        [-0.0174, -0.2324,  0.1477, -0.0108,  0.2444, -0.0510,  0.0972, -0.2087,
         -0.2384,  0.2389],
        [-0.0413,  0.1820, -0.1028, -0.0082,  0.2666,  0.2857,  0.2043, -0.0340,
         -0.2504, -0.2520],
        [ 0.2029,  0.2248,  0.1558,  0.1638, -0.1852, -0.2456, -0.1350, -0.0824,
         -0.2781, -0.0273]], requires_grad=True)

In [4]:
myLayer.bias

Parameter containing:
 0.3093
-0.1218
-0.2188
 0.0249
-0.1592
[torch.FloatTensor of size 5]

### Stacking Linear layers

In [5]:
myLayer1 = Linear(10,5)
myLayer2 = Linear(5,2)
myLayer2(myLayer1(inp))

Variable containing:
 0.4065 -0.7448
[torch.FloatTensor of size 1x2]

### PyTorch Non-linear Activations

In [7]:
sample_data = Variable(torch.Tensor([[1,2,-1,-1]])) 
myRelu = ReLU()
myRelu(sample_data)


tensor([[1., 2., 0., 0.]])

In [10]:
import torch.nn as nn
import torch.nn.functional as F
sample_data = Variable(torch.Tensor([[1,2,-1,-1]])) 
f = F.relu(sample_data) # Much simpler.
f

tensor([[1., 2., 0., 0.]])

### Neural Network 

In [24]:
class MyFirstNetwork(nn.Module):
    def __init__(self,input_size,hidden_size,output_size):
        super(MyFirstNetwork,self).__init__() 
        self.layer1 = nn.Linear(input_size,hidden_size) 
        self.layer2 = nn.Linear(hidden_size,output_size)
    def __forward__(self,input): 
        out = self.layer1(input) 
        out = nn.ReLU(out)
        out = self.layer2(out) 
        return out

### Loss

In [27]:
loss = nn.MSELoss()
input = Variable(torch.randn(3, 5), requires_grad=True) 
target = Variable(torch.randn(3, 5))
output = loss(input, target)
output.backward()

In [29]:
def cross_entropy(true_label, prediction):
    if true_label == 1:
        return -log(prediction)
    else:
        return -log(1 - prediction)

In [30]:
loss = nn.CrossEntropyLoss()
input = Variable(torch.randn(3, 5), requires_grad=True) 
target = Variable(torch.LongTensor(3).random_(5)) 
output = loss(input, target)
output.backward()

### Optimizer

In [ ]:
# for demo
import torch.optim as optim
optimizer = optim.SGD(model.parameters(), lr = 0.01)
for input, target in dataset:
    optimizer.zero_grad()
    output = model(input)
    loss = loss_fn(output, target)
    loss.backward()
    optimizer.step()