- 导包



In [9]:
import torch
import torch.nn as nn
import numpy as np
from torch.autograd import Variable
import torch.nn.functional as F

In [10]:
layer1 = nn.Linear(in_features=10,out_features=5,bias=True)
x = Variable(torch.randn(1,10),requires_grad = True)
layer1(x)

tensor([[ 0.6531, -0.5829,  0.0905, -0.5678,  0.4714]],
       grad_fn=<AddmmBackward>)

In [11]:
layer1.weight


Parameter containing:
tensor([[ 0.2804,  0.0089,  0.0423,  0.2318, -0.1032, -0.1193, -0.1484, -0.3153,
         -0.2179, -0.1867],
        [ 0.0463,  0.1581,  0.0612, -0.0212, -0.1010, -0.2694, -0.1829, -0.0109,
         -0.1963,  0.2566],
        [ 0.0182, -0.2388,  0.2120, -0.0241,  0.0007,  0.1997, -0.3047,  0.0594,
          0.0877, -0.2169],
        [-0.1564, -0.0123, -0.1121,  0.2450,  0.0887,  0.2889, -0.1648, -0.2326,
         -0.2165, -0.1255],
        [ 0.0897, -0.2626,  0.0309,  0.3046, -0.2611,  0.0547, -0.3096,  0.2623,
          0.2567, -0.0662]], requires_grad=True)

In [12]:
layer1.bias

Parameter containing:
tensor([ 0.2394, -0.3107, -0.1033, -0.0737,  0.1406], requires_grad=True)

## 堆叠线性层

In [13]:
layer1 = nn.Linear(10,5)
layer2 = nn.Linear(5,2)
layer2(layer1(x))


tensor([[-0.4208, -0.4423]], grad_fn=<AddmmBackward>)

## 非线性激活函数

In [14]:

sample_data = Variable(torch.Tensor([[1,2,-1,-2]]))
myRelu = nn.ReLU()
myRelu(sample_data)


tensor([[1., 2., 0., 0.]])

In [15]:
import torch.nn.functional as F
sample_data = Variable(torch.Tensor([[1,2,-1,-2]]))
f = F.relu(sample_data)
f

tensor([[1., 2., 0., 0.]])

## 神经网络

In [34]:
class model(nn.Module):
    def __init__(self,input_size,hidden_size,output_size):
        super(model, self).__init__()
        self.layer1 = nn.Linear(input_size,hidden_size)
        self.layer2 = nn.Linear(hidden_size,output_size)

    def __forward__(self,input):
        out = self.layer1(input)
        out = F.relu(out)
        out = self.layer2(out)
        return out


## Loss

In [40]:
# MSE
loss = nn.MSELoss()
input = Variable(torch.randn(3,5),requires_grad = True)
target = Variable(torch.randn(3,5))
output = loss(input,target)
output.backward()
output

tensor(1.5388, grad_fn=<MseLossBackward>)

In [42]:
# CrossEntropyLoss
loss = nn.CrossEntropyLoss()
input = Variable(torch.randn(3, 5), requires_grad=True)
target = Variable(torch.LongTensor(3).random_(5))
output = loss(input, target)
output.backward()
output


tensor(2.3836, grad_fn=<NllLossBackward>)

## 优化器


In [43]:
import torch.optim as optim
model = model(3,5,3)
optimizer = optim.SGD(model.parameters(), lr=1e-3, momentum=0.9)
for input, target in datasets:
    optimizer.zero_grad()
    output = model(input)
    loss = loss(output, target)
    loss.backward()
    optimizer.step()


NotImplementedError: 